import test from 'node:test';
import assert from 'node:assert/strict';
import { Town, BUFFER_MS, PRESENCE_MS, emptyState } from '../core.mjs';
const places = [{ id:'home',tenantId:'org-a',title:'Home',goal:'',role:'owner' },{ id:'cafe',tenantId:'shared',title:'Cafe',goal:'',role:'editor' }];
function fixture(){let now=1_000_000,n=0;const t=new Town(emptyState(),()=>now,()=>`id-${++n}`);const ctx=(id='alice', ps=places)=>({actor:{id,expiresAt:now+3600_000},places:ps});const send=(op,extra={},c=ctx())=>t.execute(c,{op,requestId:`req-${++n}`,roomId:'home',revision:t.room('home').revision,...extra});const join=(c=ctx(),x=0)=>{t.live(c,{op:'join',roomId:'home'});t.live(c,{op:'move',roomId:'home',x,z:0});};return{t,ctx,send,join,time:ms=>{now+=ms;}};}
test('tenant membership is not permission: hidden rooms and tasks remain hidden',()=>{const{t,ctx,send}=fixture();send('task',{title:'secret',mine:true});const guest=ctx('guest',[places[1]]);assert.equal(t.read(guest,'cafe').tasks.length,0);assert.throws(()=>t.read(guest,'home'),e=>e.status===404);assert.throws(()=>send('post',{text:'no'},guest),e=>e.status===404);});
test('read-only participants cannot persist, speak or play but can join',()=>{const{t,ctx,send,join}=fixture();const viewer=ctx('viewer',[{...places[0],role:'viewer'}]);join(viewer);assert.throws(()=>send('post',{text:'x'},viewer),e=>e.status===403);assert.throws(()=>t.whisper(viewer,{roomId:'home',text:'x'}),e=>e.status===403);assert.throws(()=>send('play',{cell:0},viewer),e=>e.status===403);});
test('nearby text only reaches recipients present, in range, and not focused',()=>{const{t,ctx,join,time}=fixture();join(ctx('alice'));join(ctx('bob'),2);join(ctx('far'),9);join(ctx('focus'),1);t.live(ctx('focus'),{op:'mode',roomId:'home',mode:'focus'});const m=t.whisper(ctx(),{roomId:'home',text:'a thought'});assert.equal(t.read(ctx('bob'),'home').buffer[0].id,m.id);assert.equal(t.read(ctx('far'),'home').buffer.length,0);assert.equal(t.read(ctx('focus'),'home').buffer.length,0);join(ctx('late'));assert.equal(t.read(ctx('late'),'home').buffer.length,0);time(1100);t.live(ctx('far'),{op:'move',roomId:'home',x:0,z:0});assert.equal(t.read(ctx('far'),'home').buffer.length,0);});
test('capturing requires actual recipient exposure, not current membership',()=>{const{t,ctx,join,send}=fixture();join();join(ctx('bob'),2);const m=t.whisper(ctx(),{roomId:'home',text:'useful'});join(ctx('late'));assert.throws(()=>send('capture',{id:m.id},ctx('late')),e=>e.status===404);send('capture',{id:m.id},ctx('bob'));assert.equal(t.read(ctx('bob'),'home').memories.length,1);assert.equal(t.read(ctx(),'home').memories.length,0);});
test('unselected text expires; selected private memory survives restart',()=>{const{t,ctx,join,send,time}=fixture();join();const m=t.whisper(ctx(),{roomId:'home',text:'save me'});send('capture',{id:m.id});time(BUFFER_MS+1);assert.equal(t.read(ctx(),'home').buffer.length,0);assert.throws(()=>send('capture',{id:m.id}),e=>e.status===404);const restored=new Town(t.durable(),()=>1_000_000+BUFFER_MS+1);assert.equal(restored.read(ctx(),'home').memories.length,1);assert.equal(restored.read(ctx(),'home').people.length,0);assert.equal(restored.read(ctx(),'home').buffer.length,0);});
test('captured memory cannot silently expand to another room or user',()=>{const{t,ctx,join,send}=fixture();join();const m=t.whisper(ctx(),{roomId:'home',text:'original scope'});send('capture',{id:m.id});const memory=t.read(ctx(),'home').memories[0];assert.throws(()=>send('share',{roomId:'cafe',revision:0,id:memory.id}),e=>e.status===403);assert.throws(()=>send('share',{id:memory.id},ctx('bob')),e=>e.status===404);send('share',{id:memory.id});assert.equal(t.read(ctx(),'home').current.posts[0].source.author,'alice');});
test('idempotency binds actor, ID and exact body; retry does not duplicate',()=>{const{t,ctx}=fixture();const command={op:'post',roomId:'home',revision:0,requestId:'stable',text:'hello'};const first=t.execute(ctx(),command);assert.deepEqual(t.execute(ctx(),command),first);assert.equal(t.room('home').posts.length,1);assert.throws(()=>t.execute(ctx(),{...command,text:'different'}),e=>e.code==='request_collision');assert.throws(()=>t.execute(ctx('revoked',[]),command),e=>e.status===404);});
test('stale revisions reject rather than overwrite or duplicate',()=>{const{t,ctx}=fixture();t.execute(ctx(),{op:'post',requestId:'r1',roomId:'home',revision:0,text:'A'});assert.throws(()=>t.execute(ctx(),{op:'post',requestId:'r2',roomId:'home',revision:0,text:'B'}),e=>e.code==='revision_conflict');assert.equal(t.room('home').posts.length,1);});
test('prepare/commit boundary does not publish unsaved data',()=>{const{t,ctx}=fixture();const before=t.durable();const p=t.prepare(ctx(),{op:'post',requestId:'r1',roomId:'home',revision:0,text:'pending'});assert.deepEqual(t.durable(),before);assert.equal(t.read(ctx(),'home').current.posts.length,0);t.commit(p);assert.equal(t.read(ctx(),'home').current.posts.length,1);});
test('ephemeral presence and whisper bodies never enter durable state',()=>{const{t,ctx,join}=fixture();join();t.whisper(ctx(),{roomId:'home',text:'ephemeral-secret'});const value=JSON.stringify(t.durable());assert.ok(!value.includes('ephemeral-secret'));for(const term of ['seenAt','gestureAt','recipients','expiresAt'])assert.ok(!value.includes(term));});
test('invalidation clears presence and rewind; former access does not reveal private memory',()=>{const{t,ctx,join,send}=fixture();join();const m=t.whisper(ctx(),{roomId:'home',text:'private'});send('capture',{id:m.id});t.invalidate();assert.equal(t.read(ctx(),'home').people.length,0);assert.equal(t.read(ctx(),'home').buffer.length,0);assert.equal(t.read(ctx('alice',[]),'').memories.length,0);});
test('presence expires without creating attendance history',()=>{const{t,ctx,join,time}=fixture();join();time(PRESENCE_MS+1);assert.equal(t.read(ctx(),'home').people.length,0);assert.equal(Object.keys(t.durable().rooms).length,0);});
test('expired identity is rejected on reads and mutations',()=>{const{t,ctx}=fixture();const c=ctx();c.actor.expiresAt=1;assert.throws(()=>t.read(c,'home'),e=>e.status===401);assert.throws(()=>t.execute(c,{op:'profile',requestId:'r'}),e=>e.status===401);});
test('tasks aggregate only authorized places; claiming is explicit',()=>{const{t,ctx,send}=fixture();send('task',{title:'first',mine:true});send('task',{roomId:'cafe',revision:0,title:'second',mine:false});assert.equal(t.read(ctx(),'home').tasks.length,2);const task=t.room('cafe').tasks[0];send('taskUpdate',{roomId:'cafe',revision:1,id:task.id,claim:true},ctx('bob'));assert.equal(t.room('cafe').tasks[0].assignee,'bob');assert.throws(()=>send('taskUpdate',{roomId:'cafe',revision:2,id:task.id,claim:true}),e=>e.status===403);});
test('guest identity and roles cannot be set via profile input',()=>{const{t,ctx,send}=fixture();send('profile',{name:'hello',avatar:'cat',color:'sage',guest:false,role:'owner'});const s=t.read({...ctx(),actor:{...ctx().actor,guest:true}},'home');assert.equal(s.actor.guest,true);assert.equal(t.state.profiles.alice.role,undefined);});
test('prototype keys, invalid coordinates and oversized text fail safely',()=>{const{t,ctx,join,send}=fixture();assert.throws(()=>t.read(ctx('__proto__'),'home'),e=>e.status===401);join();assert.throws(()=>t.live(ctx(),{op:'move',roomId:'home',x:NaN,z:0}),e=>e.status===400);assert.throws(()=>send('post',{text:'x'.repeat(8001)}),e=>e.status===400);assert.equal({}.polluted,undefined);});
test('a reply must belong to the same room',()=>{const{t,send}=fixture();send('post',{text:'home'});assert.throws(()=>send('post',{roomId:'cafe',revision:0,text:'reply',parentId:t.room('home').posts[0].id}),e=>e.status===404);});
test('only original author or owner can remove another persons object/post',()=>{const{t,ctx,send}=fixture();send('post',{text:'one'});assert.throws(()=>send('deletePost',{id:t.room('home').posts[0].id},ctx('bob',[{...places[0],role:'editor'}])),e=>e.status===403);});
test('shared game requires two different people and validates turns',()=>{const{t,ctx,send}=fixture();send('play',{cell:0});assert.throws(()=>send('play',{cell:1}),e=>e.status===403);send('play',{cell:3},ctx('bob'));send('play',{cell:1});send('play',{cell:4},ctx('bob'));send('play',{cell:2});assert.equal(t.room('home').game.winner,'○');});
test('plants are durable, water is bounded; photo SVG and external URLs rejected',()=>{const{t,send}=fixture();send('object',{kind:'plant',label:'olive'});const o=t.room('home').objects[0];send('water',{id:o.id});assert.throws(()=>send('water',{id:o.id}),e=>e.code==='already_watered');assert.throws(()=>send('object',{kind:'photo',label:'bad',image:'data:image/svg+xml;base64,AAAA'}),e=>e.status===400);assert.throws(()=>send('object',{kind:'photo',label:'bad',image:'https://example.com/track'}),e=>e.status===400);});
test('old durable posts stay searchable, unlike five-minute whispers',()=>{const{t,send,ctx,time}=fixture();send('post',{text:'the old decision'});time(180*86_400_000);assert.equal(t.read(ctx(),'home','old decision').search.length,1);});

test('old pinned posts and thread roots are retained in the default board',()=>{
  const {t,ctx,send}=fixture();const root=send('post',{text:'old root'}).id;send('pin',{id:root});
  for(let n=0;n<155;n++)send('post',{text:`later ${n}`});
  const reply=send('post',{text:'new reply',parentId:root}).id;
  const board=t.read(ctx(),'home').current;assert.equal(board.totalPosts,157);
  assert.ok(board.posts.some(p=>p.id===root&&p.pinned));assert.ok(board.posts.some(p=>p.id===reply&&p.parentId===root));
});
test('compact movement events exclude durable work and private memories',()=>{
 const{t,ctx,join,send}=fixture();send('post',{text:'durable private context'});join();const m=t.whisper(ctx(),{roomId:'home',text:'a moment'});send('capture',{id:m.id});
 const event=t.presenceSnapshot(ctx(),'home');assert.equal(event.kind,'presence');for(const key of ['current','tasks','memories','search','recipients'])assert.ok(!(key in event));assert.doesNotMatch(JSON.stringify(event),/durable private context/);
});
test('malformed commands fail as validation errors without mutating state',()=>{const{t,ctx}=fixture();for(const input of [null,[],42])for(const method of ['live','whisper','prepare'])assert.throws(()=>t[method](ctx(),input),e=>e.status===400);assert.deepEqual(t.durable(),emptyState());});
test('capacity guard rejects new work without deleting existing work',()=>{const{t,ctx,send}=fixture();send('post',{text:'retain me'});t.state.profiles.extra={name:'x'.repeat(4*1024*1024),avatar:'person',color:'sage'};const before=t.durable();assert.throws(()=>send('post',{text:'too much'}),e=>e.code==='pilot_capacity');assert.deepEqual(t.durable(),before);});
