import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { startTown } from '../server.mjs';
async function login(app,actor){const r=await fetch(app.origin+'/local/session',{method:'POST',headers:{Origin:app.origin,'Content-Type':'application/json','X-Engawa-Client':'town-ui'},body:JSON.stringify({actor})});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];}
async function call(app,cookie,method='GET',input,path='/api/town?room=garden',extra={}){return fetch(app.origin+path,{method,headers:{Cookie:cookie,Origin:app.origin,'Content-Type':'application/json','X-Engawa-Client':'town-ui',...extra},body:input?JSON.stringify(input):undefined});}
test('real HTTP, two sessions, streamed presence and private rewind',async()=>{const app=await startTown({port:0,dbPath:':memory:',seed:false});try{const a=await login(app,'aoi'),b=await login(app,'sora');for(const c of [a,b])assert.equal((await call(app,c,'POST',{op:'join',roomId:'garden'})).status,200);const r=await call(app,b,'GET',undefined,'/api/town/events?room=garden&actor=sora');assert.equal(r.status,200);const reader=r.body.getReader();const first=new TextDecoder().decode((await reader.read()).value);assert.match(first,/"id":"aoi"/);await reader.cancel();const w=await (await call(app,a,'POST',{op:'whisper',roomId:'garden',text:'in the same place'})).json();const before=await (await call(app,b)).json();assert.equal(before.buffer[0].text,'in the same place');assert.equal((await call(app,b,'POST',{op:'capture',roomId:'garden',requestId:'save-1',id:w.id})).status,200);assert.equal((await (await call(app,b)).json()).memories.length,1);assert.equal((await (await call(app,a)).json()).memories.length,0);}finally{await app.close();}});
test('HTTP rejects foreign origin, wrong actor, unknown room and guest boundary',async()=>{const app=await startTown({port:0,dbPath:':memory:'});try{const a=await login(app,'aoi'),g=await login(app,'guest');assert.equal((await call(app,a,'POST',{op:'join',roomId:'garden'},'/api/town',{Origin:'https://evil.test'})).status,403);assert.equal((await call(app,a,'GET',undefined,'/api/town',{'X-Engawa-Actor':'sora'})).status,401);assert.equal((await call(app,g,'GET',undefined,'/api/town?room=atelier')).status,404);const snapshot=await (await call(app,g)).json();assert.ok(!snapshot.places.some(p=>p.id==='atelier'));assert.ok(!snapshot.tasks.some(t=>t.roomId==='atelier'));assert.equal((await call(app,a,'GET',undefined,'/api/unknown')).status,404);}finally{await app.close();}});
test('SQLite persists explicit work across a real restart, not people or whispers',async()=>{const dir=await mkdtemp(join(tmpdir(),'town-test-')),dbPath=join(dir,'db.sqlite');let app=await startTown({port:0,dbPath,seed:false});try{let a=await login(app,'aoi');await call(app,a,'POST',{op:'post',roomId:'garden',revision:0,requestId:'durable-one',text:'survives restart'});await call(app,a,'POST',{op:'join',roomId:'garden'});await call(app,a,'POST',{op:'whisper',roomId:'garden',text:'not durable'});await app.close();app=await startTown({port:0,dbPath,seed:false});a=await login(app,'aoi');const state=await (await call(app,a)).json();assert.equal(state.current.posts[0].text,'survives restart');assert.equal(state.people.length,0);assert.equal(state.buffer.length,0);}finally{await app.close();await rm(dir,{recursive:true,force:true});}});
test('runtime rejects oversized input and proxy headers; demo styling can load without session',async()=>{const app=await startTown({port:0,dbPath:':memory:'});try{const a=await login(app,'aoi');assert.equal((await call(app,a,'POST',{text:'x'.repeat(66000)})).status,413);assert.equal((await call(app,a,'GET',undefined,'/api/town',{'X-Forwarded-Host':'public.test'})).status,403);const css=await fetch(app.origin+'/style.css');assert.equal(css.status,200);assert.match(css.headers.get('content-type'),/text\/css/);const root=await fetch(app.origin+'/',{redirect:'manual'});assert.equal(root.status,302);}finally{await app.close();}});
